version: "3.8"

services:
  bankdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root!238Ji*"
      POSTGRES_DB: "atm"
  bank:
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - bankdb
